# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'SC'
    organization: 'DedalusAPAC'
    # sonar.exclusions=**/*.bin
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=CCReport43F6D5EF/jacoco.xml
      # Initial behavior of Maven task is that the SonarScanner uses information contained in Maven
      # object model to provide smart defaults for most of the standard analysis parameters.
      # You can however override this by setting wanted properties in this extraProperties space.
      # Read more about this : https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/#header-4

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dmaven.test.failure.ignore=true'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    sonarQubeRunAnalysis: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sqMavenPluginVersionChoice: 'latest'
    codeCoverageToolOption: 'JaCoCo'
    testResultsFiles: '**/TEST-*.xml'
    goals: 'verify'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'